ScrollText      db      2
                db      'greetings fellow demo dudes..... this was my first'
                db      ' intro i did with a sinus scroller.... it looks really'
                db      '   cool     ',0,'           ',2
                db      'yea.. i think that this is a bit old now but i still'
                db      ' had it lying around on my harddrive. amazing, coz i '
                db      'usually delete old stuff.......... anyway, '
                db      'all good things come to an end and even not so good things'
                db      ' too.. so bye for now peops... frenzy signing off...'
                db      '               '
                db      '          ',255

SmallText       db      '       this is frenzy typing...        ',1
                db      '  inspired by the slipstream demo by   ',1
                db      '    micron i thought i would get my    ',1
                db      '  first intro i have ever done and use ',1
                db      '  it to get all other members of their ',1
                db      '   arses... come on!!!! get a move on  ',1
                db      '  ------------------------------------ ',1
                db      '     code for this little intro is...  ',1
                db      '          code, design : frenzy        ',1
                db      '                 bye bye               ',1
                db      '                                       ',1
                db      '                                       ',1
                db      0
