#ifndef __TYPEDEF_H
#define __TYPEDEF_H

#ifndef NULL
#define NULL 0x0
#endif
typedef unsigned char ubyte;
typedef unsigned char UBYTE;
typedef unsigned char uchar;
typedef unsigned char UCHAR;
typedef char byte;
typedef char BYTE;
typedef unsigned short uword;
typedef unsigned short UWORD;
typedef short word;
typedef short WORD;
typedef unsigned int udword;
typedef unsigned int UDWORD;
typedef unsigned int uint;
typedef unsigned int UINT;
typedef int dword;
typedef int DWORD;


#endif
